### ISSUE TITLE
Use logarithmic volume scaling

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/lozya#23]
HTML5 audio volume setting seems to provide for a linear response. I couldn't tell at first, but after testing for a while, it seems pretty clear, given there is very little volume drop off until you reach the edge of the hearing range.

**Comment by capnmidnight** [comment]
I think this can be done by just calling Math.sqrt() on the final volume value calculated in user.js/readUser

**Comment by capnmidnight** [comment]
I pushed out the change, but we'll have to test it live to see if it's any good.

**Comment by hilarysk** [comment]
Hello! A friend sent me this and I've been playing around. Not sure if these changes are live yet, but the issue still appears to be happening, fwiw.

**Comment by capnmidnight** [comment]
Yeah, the previous change I made just made the problem worse. That's what I get for trying to visual curves in my head.

I pushed out another tweak this morning and was able to test it a little bit ago. It *seems* better. Let me know what you think.

**Comment by hilarysk** [comment]
Just tested it, and it seems much better ❤️ Nice work!
